repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
        stages: [manual]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: no-commit-to-branch
        args:
          - --branch=main
  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.7.0
    hooks:
      # Run `python-typing-update` hook manually from time to time
      # to update python typing syntax.
      # Will require manual work, before submitting changes!
      # pre-commit run --hook-stage manual python-typing-update --all-files
      - id: python-typing-update
        stages: [manual]
        args:
          - --py310-plus
          - --force
          - --keep-updates
        files: ^.*\.py$
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
