[build-system]
requires      = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name            = "pydrawise"
description     = "Python API for interacting with Hydrawise sprinkler controllers."
authors         = [
    {name = "David Knowles", email = "dknowles2@gmail.com"},
]
dependencies    = ["aiohttp ", "apischema", "gql", "graphql-core", "requests"]
requires-python = ">=3.11"
dynamic         = ["readme", "version"]
license         = {text = "Apache-2.0"}
keywords        = ["hydrawise", "api", "iot"]
classifiers     = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.optional-dependencies]
docs = ["mkdocs==1.6.1", "mkdocstrings==1.0.6", "mkdocstrings-python==2.0.5"]

[project.urls]
"Homepage"      = "https://github.com/dknowles2/pydrawise"
"Source Code"   = "https://github.com/dknowles2/pydrawise"
"Bug Reports"   = "https://github.com/dknowles2/pydrawise/issues"

[dependency-groups]
test = [
    "freezegun==1.5.5",
    "mypy==2.3.0",
    "pytest==9.1.1",
    "pytest-asyncio==1.4.0",
    "ruff==0.16.0",
    "types-requests==2.33.0.20260712",
]
dev = [{ include-group = "test" }, "pre-commit==4.6.1"]

[tool.setuptools]
platforms            = ["any"]
zip-safe             = true
include-package-data = true

[tool.setuptools.dynamic]
readme          = { file = ["README.md"], content-type = "text/markdown" }

[tool.setuptools_scm]
write_to = "pydrawise/_version.py"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.ruff.lint]
ignore = ["DTZ", "RUF009"]

