name: Publish to PyPI

on:
  release:
    types: [published]

permissions: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'
      - name: Install uv
        run: python -m pip install uv
      - name: Build
        run: uv build
      - name: Upload distributions
        uses: actions/upload-artifact@v7.0.1
        with:
          name: dist
          path: dist/

  publish:

    needs: build
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v8.0.1
        with:
          name: dist
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.14.2
